### ISSUE TITLE
rubyLocalVariableOrMethod color not changeable

### ISSUE THREAD

**Issue by cseelus** [vim-ruby/vim-ruby#211]
Line 92 of `syntax/ruby.vim` seems to overwrite color scheme settings for `rubyLocalVariableOrMethod`.

Also see [this Stackexchange answer](http://stackoverflow.com/a/23161539/973852) (not from me) for further information.

**Comment by ifonefox** [comment]
It looks like rubyLocalVariableOrMethod isn't mapped to a highlight in the highlight definition section. This makes it look like the developers intentionally chose to "display transparent", so that they have no special color. This makes it consistent with the syntax highlighting for other languages, like javascript and python.

**Comment by dkearns** [comment]
Syntax groups defined with the transparent tag aren't intended to be highlighted.

Think of it as a private implementation detail.
