### ISSUE TITLE
Improve performance with syntax file (look-behind patterns: limit to length/bytes)

### ISSUE THREAD

**Issue by blueyed** [vim-ruby/vim-ruby#243]
From [this discussion](https://groups.google.com/forum/#!topic/vim_dev/tTyRMSakpSI), Ruby highlight was especially slow after the introduction of the new regex engine, due to frequent use of zero-width look-behind assertions \@<! and \@<= without using the character-limiting features added to address the problem of their slowness in the new engine (:help /\@<= , :help /\@<! , scroll down to the part about limiting by bytes).

Looking at https://github.com/vim-ruby/vim-ruby/blob/master/syntax/ruby.vim this issue was never fully addressed, only for one of the occurrences. 

Via https://groups.google.com/d/msg/vim_dev/O7GuJkbH9tk/IEMJqWt3SN8J

**Comment by chrisbra** [comment]
Please also take a look at [issue 282](https://code.google.com/p/vim/issues/detail?id=282) from the vim bugtracker. There are some serious expansive patterns in the syntax (rubySymbol and rubyPredefinedConstant) file. You might want to explicitly use the old backtracing engine for those patterns or try to limit the look-around assertions if it is not possible to further tune those patterns.

**Comment by gpakosz** [comment]
Please see https://github.com/vim/vim/issues/282#issuecomment-169837021 where I mentioned `rubyConditionalExpression` causing lag.

**Comment by benoittgt** [comment]
It seems that people from `vim/vim` forward you here and people on `vim-ruby` forward you to vim... 

But what can we do. This for me "the" problem in vim actually..

**Comment by blueyed** [comment]
@benoittgt 
I've created the issue for vim-ruby, because it can be fixed here - although I do not use it myself (I've just stumbled upon it back then).
(Unsubscribing from this issue)

**Comment by bluz71** [comment]
This is still a genuine issue. Same goes for [Vim 282](https://github.com/vim/vim/issues/282).

I have *relativenumber* set and scrolling RSpec files was borderline unusable on a CoreM powered Macbook (aka a slower Mac) using iTerm2 with both Vim 8 and Neovim. 

Setting *lazyredraw* slightly mitigates this issue, but it has other negative effects so I do not set it.

Setting *set regexpengine=1* at the global level fixed the issue for me. Note, setting *regexpengine=1* in an *autocmd FileType ruby* resulted in no performance difference, only setting the *regexpengine* at the top level worked. Why is that? Weird.

Anyway, *vim-ruby* clearly has performance issues with *relativenumber* and the newer Vim *regexpengine* (which is now the default). Doing some [Googling](https://www.google.com/search?q=set+regexpengine%3D1) seems to indicate that many Ruby folks are experiencing this issue

Maintainers, please test *vim-ruby* with both the old and new *regexpengine* (on slow machines), there is a clear performance regression with some *vim-ruby* rules when run against the new engine.

**Comment by tpope** [comment]
Friendly reminder that maintainers are not your personal servants. If you wanna get this fixed, provide a patch or a paycheck, or at the very least do a fresh assessment of which patterns are the bottleneck.

**Comment by bluz71** [comment]
Agreed, I do genuinely apologise if offence was taken, it was not the intention, though rereading my post I can see how that may have been the case.

I will try and make myself useful and I will provide as many details as possible soon: syntimes, CPU usage and possibly which patterns are the expensive ones. Details to follow.

My gut feeling is that *vim-ruby* syntax highlighter is triggering some expensive CPU processing with the newer NFA engine. Folks with fast CPUs are likely not seeing the issue, those with slower machines notice a *huge* performance issue. The old regexp engine is likely much lighter on CPU.

The first posts of [vim issue 282](https://github.com/vim/vim/issues/282) perfectly detail the issue.

**Comment by bluz71** [comment]
Results,

- 2015 Macbook with slow CoreM processor (1.1GHz)
- Vim 8 in iTerm2 (3.0.15) with tmux (2.4) (note, Neovim 0.2 has the same issue)
- Latest vim-ruby
- relativenumber is set (this is the main trigger)
- *foldmethod=indent* (not *syntax* which I know is expensive)

**syntime on** / **syntime report** produced no meaningful culprit between my fast mode (*regexpengine=1*) or my slow mode (*regexpengine=0 or 2*).

CPU results:
- *regexpengine=1* resulted in **MAX** CPU usage of 85% (usually around 80%)
- *regexpenging=2* resulted in **MAX** CPU usage of 100% (usually around 96%)

There is **no** single bad rule in the *vim-ruby* syntax highlighter. Basically you have to comment out half the file to get reasonable performance. Even enabling **let ruby_no_expensive = 1** had no meaningful performance benefit on my rig.

On my slow Macbook *regexpenging=1* does not max the CPU hence why it has such a massive benefit for me. However if *vim-ruby* had a few more rules then even that old engine would be cooked I suspect.

I think the issue is the number of rules in *vim-ruby* in combination with Vim not-caching syntax results when *relativenumber* is enabled **AND** a slow CPU. Disabling *relativenumber* is a fix (but one I am not willing to do since *relativenumber* is so useful); setting *lazyredraw* somewhat addresses the issue as well (but it causes other worse problems).

I believe the best solution lies with a fix in Vim / Neovim itself for *relativenumber* or *cursorline* modes, that being to cache syntax highlighting and not recalculate when scrolling. The recalculation is the killer. Bram himself suggested it 18 months ago [here](https://github.com/vim/vim/issues/282#issuecomment-164013461).

I don't think *vim-ruby* maintainers can really do that much to fix this **open** except to encourage Bram and the Neovim teams to *cache* and *cache some more*. Luckily Bram himself suggested the actual fix.

**Comment by tpope** [comment]
If it's fine without `'relativenumber'` then I agree, it's not something that can be solved with changes to vim-ruby.

**Comment by bluz71** [comment]
Tim,

```relativenumber``` is key here, when enabled each scroll event (up or down) forces a full syntax highlight cycle for every visible line since each line subtly changes (in the number column).

*vim-ruby* syntax has about 240 regexps, multiply by the number of visible lines results in a lot of syntax work when ```relativenumber``` is enabled. When ```relativenumber``` is not enabled, no issue at all.

I have spawned a [new feature request](https://github.com/vim/vim/issues/1735) over in the Vim repository, that being *syntax highlight caching*, a suggestion Bram himself noted in [#282](https://github.com/vim/vim/issues/282). I suspect it is not an easy request to implement, so may not happen.

As for here, I doubt there is anything that can be done in *vim-ruby* repository to address this specific issue. *The fix* needs to occur upstream.

Lastly, I do appreciate all the work maintainers do, thank you.

**Comment by juanibiapina** [comment]
For me it's not fine without `relativenumber`. It's better, but still slow.

Using `regexpengine=1` makes it as fast as neovim (which doesn't have that problem regardless of the config o.O).

**Comment by bluz71** [comment]
Vim commit [bd9a53c](https://github.com/vim/vim/commit/bd9a53c06c8869ad811cb3dd01a309c9be7d7a63) (patch 8.1.0374) implements a `relativenumber` optimisation, _only redraw the number column, not all lines_.

I have updated and tested with that patch, and indeed scrolling within a page of Ruby code, with `relativenumber` enabled, is now much smooth.

I still set:

```viml
set ttyfast
set regexpengine=1
```

With that combination of Vim & Regex engine Ruby performance in Vim is fine (for me). Regex version 1 helps very much from my previous testing, if version 2 is slower than 1 is that not an upstream Vim issue not a vim-ruby issue?

I tend to believe this can be resolved.

**Comment by bluz71** [comment]
Sorry to bump this, but the following information may be of interest to folks still having performance issues with Ruby in (Neo)Vim editors.

The Neovim team have incorporated [Treesitter](https://github.com/tree-sitter/tree-sitter) in the upcoming 0.5 release, which includes a Ruby parser (among many other supported languages).

Treesitter does semantic incremental parsing (in optimised C code). It understands language to a certain extent. An analogy would be:

- Treesitter is to Regular Expression highlighting
- As Language Server Protocol is to `ctags`

Treesitter, in my experience, solves two concerns with the existing Vim regular expression based highlighting mechanism: performance and correctness. The performance side is especially noticeable (in favour of Treesitter).

For folks who still have performance or correctness issues with Ruby in Vim, then it may be worth giving Neovim 0.5 + Treesitter Ruby a go. It completely avoids the regular expression highlight subsystem of Vim which is the cause of this and many other quirky highlight issues.

Best regards.

P.S. I am not part of the Treesitter or Neovim teams, just a Rubyist that uses (Neo)Vim editors.
