### ISSUE TITLE
Setting syntax fold selectively

### ISSUE THREAD

**Issue by bruno-** [vim-ruby/vim-ruby#258]
Hi,
thanks to all the maintainers for working on this plugin!

I have a question around syntax folds. I find the folding too "granular" with `let ruby_fold = 1`. It is as if it is too much work to get to the actual code when this is set.

I've tried editing `syntax/ruby.vim` locally by removing all the `fold` options and leaving it only for `rubyMethodBlock`. This works perfectly.

Is there a way to achieve this in a more elegant way than editing ruby syntax file locally?

Thanks a lot!

**Comment by AndrewRadev** [comment]
One simple way to get this done is to copy the relevant lines in `syntax/ruby.vim` to your own `~/.vim/after/syntax/ruby.vim` and override them there. The new lines should have effect (though I haven't tried it myself). This still means you need to copy the lines, which means if they change, you might have problems, but the ruby syntax files don't change that often, so it shouldn't be a big deal.

Alternatively, you could write your own fold expression. See `:help 'foldexpr'` and then `:help fold-expr` for details. I tried to whip something up that just folds functions and ended up with:

``` vim
setlocal foldmethod=expr
setlocal foldexpr=RubyFold(v:lnum)

function! RubyFold(lnum)
  if getline(a:lnum) =~ '^\s*def\>'
    return ">1"
  else
    return "="
  endif
endfunction
```

I also have a more sophisticated folding setup that I haven't used in a long time [here](https://github.com/AndrewRadev/Vimfiles/blob/e73df7a94e7fe3f06ad2d6bf7cd7dde880d4a7a2/personal/plugin/rubyfold.vim). However, this doesn't use foldexpr, just manually goes over the file upon editing and creates the necessary folds. Which is why I wouldn't recommend using it other that for learning purposes if you happen to have a lot of time on your hands :).

**Comment by bruno-** [comment]
Hi Andrew,
thanks for your response.. Now I'm at least sure there are no other options than going for `after/syntax/ruby.vim`.

As for writing a custom `foldexpr`, I already went through that with [vim-ruby-fold](https://github.com/bruno-/vim-ruby-fold). It's based on detecting line syntax highlighting and folding based on that. Works fine but it's slow-ish for ruby files with 1000+ LOC.

Anyway, thanks for the response.

**Comment by bootleq** [comment]
Hi, how about introducing new option?

I have some custom syntax fold, and found it's really hard to do finer control with current fold defaults.

I'm proposing a option like `let ruby_foldable_groups = '% if'`
https://github.com/bootleq/vim-ruby/blob/fold/doc/ft-ruby-syntax.txt#L43-L61

Appreciate if any idea.

**Comment by bruno-** [comment]
I would really like the option to configure this :+1:
