### ISSUE TITLE
html erb indent

### ISSUE THREAD

**Issue by WojtekKruszewski** [vim-ruby/vim-ruby#271]
Got:

```
<%= wrapper do %>
  <%= first do
    something
  end %>

<%= second do
  something
end %>

<% end %>
```

Expected:
```
<%= wrapper do %>
  <%= first do
    something
  end %>

  <%= second do
    something
  end %>

<% end %>
```

Basically, second block should be indented too.

Fortunately this form is indented correctly:

```
<%= wrapper do %>
  <%= wrapper do %>
    <%= something %>
  <% end %>
  <%= wrapper { something } %>
<% end %>
```

**Comment by AndrewRadev** [comment]
Sorry it took a while to get to your issue.

I think that this happens due to an old commit, https://github.com/vim-ruby/vim-ruby/commit/607d143cc0055d4c8c19740068056a54feea78cd, by @tpope. This fixes an issue with similar constructs, which don't end in an `end`. I think the problem here is that the `end` itself reduces the indentation level, so it's being reduced twice.

I've pushed a possible workaround. Please try out the latest master and let me know if it seems to work for you.

**Comment by WojtekKruszewski** [comment]
Works like a charm! Thank you for working on Open Source @AndrewRadev.

**Comment by AndrewRadev** [comment]
Thank you for your kind words :). Closing the issue for now, if anyone can see potential issues, please comment and possibly reopen.
