### ISSUE TITLE
Indent correctly with chaining methods with do/end

### ISSUE THREAD

**Issue by teoljungberg** [vim-ruby/vim-ruby#273]
When I have a method that looks like:

```ruby
def some_method(collection)
  result = collection.
    select { |element| do_something_to_the_element(element) }.
    map do
      do_something_strange_to_the_element_so_this_line_goes_over_80_characters_like_it_should_not_do
    end


    this_line_should_be_outdented_one_level_but_is_not
end
```

Vim will indent `this_line_should_be_outdented_one_level_but_is_not` to the same level as the last `end`  of the `select` block. When I expect it to be indented the same as `result`

**Comment by teoljungberg** [comment]
This is using the latest `vim-ruby` from the `master` branch.
And using `vim 7.4.891`

**Comment by lamont-granquist** [comment]
seems related to #250

**Comment by teoljungberg** [comment]
https://github.com/vim-ruby/vim-ruby/pull/292 seems to fix the issue.

**Comment by AndrewRadev** [comment]
Sorry for taking so long to get to this issue.

So, I've just pushed a commit that fixes the problem, but likely not in the way you'd prefer. If you pull master now, the result you'll get will be (hopefully):

``` ruby
def some_method(collection)
  result = collection.
    select { |element| do_something_to_the_element(element) }.
    map do
    do_something_else
  end

  this_line_should_be_outdented_one_level_but_is_not
end
```

The `collection.select { }.map` is considered a single line broken up by dots, and the block's contents align to the `result =` line rather than the immediate parent.

However, as you've noticed, #292 has something to do with this, and I've merged that one as well. So, if you change a setting like so:

``` vim
:let g:ruby_indent_block_style = 'do'
```

Then the result you'll (hopefully) get is what you expected:

``` ruby
def some_method(collection)
  result = collection.
    select { |element| do_something_to_the_element(element) }.
    map do
      do_something_else
    end

  this_line_should_be_outdented_one_level_but_is_not
end
```

Let me know what you think.

**Comment by teoljungberg** [comment]
Setting `:let g:ruby_indent_block_style = 'do'` works as intended. Any reason why that is not the default?

Thanks for fixing the issue!

**Comment by AndrewRadev** [comment]
Ugh, I was planning on commenting, but, as often happens with me and this project, I left it in the queue and it ended up almost-forgotten. Sorry about that.

There's a long, long conversation in https://github.com/vim-ruby/vim-ruby/issues/250 on the topic. Maybe this comment is a good summary, not sure: https://github.com/vim-ruby/vim-ruby/issues/250#issuecomment-81152619. The short version is, both versions of the do-blocks look correct to me in different contexts, and I really can't tell which one *should* be the default. If we can find out which one is the more "popular", whatever that means, I could change the default, but I'm not sure how much it matters.
