### ISSUE TITLE
Blocks with nested array capture (Indent)

### ISSUE THREAD

**Issue by dsferreira** [vim-ruby/vim-ruby#302]
I'm using latest code from Janus.
I imagine it is up to date with vim-ruby.
When I try to indent the following block I get this behaviour for the second line of the block:

``` ruby
foo.each do |(bar)|
   qux = bar + 'baz'
puts qux
end
```

**Comment by smackesey** [comment]
Yep,  indentation has been generally messed up for several months. Whoever last made changes to the indent code should have a look at what they did. I have problems with not only blocks, but also nested hashes.

**Comment by AndrewRadev** [comment]
@dsferreira This example seems to indent correctly for me right now. It's possible Janus has an old version, but it's also possible that a fix for a different issue fixed this as well. Could you check and see if it works okay for you now as well? If not, could you try to update your vim-ruby to the latest master?

@smackesey If you have discovered it was "generally messed up" for months, it would be useful to get an example from you, in an issue. While it's true that we take way too long to work on issues, it's still quite a lot better to get a concrete example of a problem, rather to be told it's "generally messed up". If you have already opened an issue, perhaps you could link it here, so we can see if the two are connected.

> Whoever last made changes to the indent code should have a look at what they did.

Maybe you could take a look at the git logs for the last several months, and then demonstrate what was done to make it "generally messed up"? If you provide a fix in a PR, I'd be quite happy to review it.

**Comment by smackesey** [comment]
@AndrewRadev I apologize if my tone sounded entitled, but there are no less than **16** open issues with the `indent` label right now. That's plenty of concrete problems for you. Doesn't "generally messed up" describe this scenario pretty well? I take your point that it's more useful to provide pointers to specifics, but this is time-consuming and, given the large number of preexisting issues, likely duplicating effort. Yes, I could take a look at the git logs and try to figure out exactly where things went wrong, but it makes much more sense for somebody already familiar with the indent code, who altered it recently, to do this. Not everyone who reports problems should be expected to dive into the source of an unfamiliar codebase. I'm not *demanding* someone do it right now, just reporting that I have experienced a lot of problems.

**Comment by AndrewRadev** [comment]
@smackesey Any recent changes that have been made were made to fix issues that were opened on vim-ruby. If you feel that there have been problems in the last few months, they were probably caused by *fixes*. One fix may break something that used to be working correctly. It's very, very difficult to figure out how to fix one issue without introducing new ones. This is not a codebase that's particularly easy to work with. Even if you're not familiar with it, I *highly* recommend you take a look at the top of the `indent/ruby.vim` file, just so you can get a feel for the big batch of large, complicated regular expressions that are used all around the code. I promise you, the regexes are the easy part.

Here's a fun example, consider a hanging pipe:

``` ruby
foo | bar |
  baz
```

Identifying this can just mean looking for a pipe at the end of the line (if it's not a string, ignoring comments, etc. etc.). However, this code also ends with a pipe:

``` ruby
foo do | bar |
  baz
end
```

So, is that a block, or a hanging pipe? Only way is to check that the hanging pipe is *not* also part of a block, so you definitely have to check the block-ness *first* and act on it. Note that, the "hanging pipe" generalizes to a "hanging operator", really, but this particular case makes this particular operator a bit more special. If you'd like to have some fun with that, try to find this logic in the code. It usually takes me quite a while, and, as you pointed out, I've worked with the codebase a lot more than you have.

If you'd like to consider this state of things "generally messed up", it was like this before I joined the project years ago. Ruby indentation works super great for many, many use cases. I hope you'll at least agree to that. It is, however, absolutely true that there are edge cases that are not handled well, and it's difficult both to identify them (most people just run into them accidentally), and to fix them without breaking something else. 

I would like to say I do my best, but honestly, I just try to put in some effort every once in a while. There are many open issues, some of which are literally impossible to fix without some serious rewriting of at least part of the code (which would break *a lot* of things, I'm sure, and it would take a long, concentrated amount of effort, which I consider every once in a while, but never commit to), and the code is not exactly fun to work with. I try to at least explain how things work and why things break when I resolve or discuss issues, so other people can get what's going on.

I don't expect anybody to jump in and fix things. I do at least hope that people appreciate the difficulty of fixing things. And I meant what I said -- if you would like to read the codebase, look for problems and try to propose fixes, I could at least tell you what might work and what might not. That's how I started working on the codebase years ago -- I had an issue, I did *a lot* of debugging, and proposed and discussed a fix. I did this several times, and I was given commit access. Just pointing this out.

Anyway, I've responded to your example. I might try to do a sweep of the issues soon, see if I can get something fixed, but I make no promises.

**Comment by smackesey** [comment]
@AndrewRadev Your effort is much appreciated. I have experienced the pain of long VimL regex code in other contexts and I know that VimL is not exactly the easiest language to work with (now if only [Neovim](https://neovim.io/) would come along a bit quicker...). A couple months ago there was a vim-ruby update (likely fixing some other issue) that did seem to break indentation in several cases involving nested blocks and hashes, but this does seem to have been resolved recently. Thanks again for your hard work!

**Comment by dsferreira** [comment]
I can confirm that this is fixed for stable-20160928

**Comment by dsferreira** [comment]
@AndrewRaved, wouldn't it be possible to create unit tests for vim scripts? That would at least avoid the breakage of existing functionality. Is this something tried by any one?
There seems to be attempts to put vim unit tests in place like [vim unittest](https://github.com/h1mesuke/vim-unittest) but it hasn't been updated for 5 years it seems.

In terms of tests for indentation we had to create example ruby scripts and compare the indentation after running vim indentation through them.

Does it make any sense?

**Comment by AndrewRadev** [comment]
It does make sense! Which is why we're already doing it with RSpec: https://github.com/vim-ruby/vim-ruby/tree/master/spec/indent :). I try to add a new test whenever there's an issue, I put comments with the link to the original example. This does catch some issues, but many regressions are just unexpected and rely on a complicated set of conditions to trigger. Sometimes, there are even issues that only show up *as you type*, but are not problems if you manually reindent. Those I don't really know how to test, but they're pretty rare, thankfully.

If you can see some common scenarios that aren't covered by these tests, I would be happy to review and possibly merge them. Right now, I only add tests whenever I fix an issue, to prevent it from reoccurring. I'm pretty sure that tests don't cover the full functionality of the plugin.
