### ISSUE TITLE
block with trailing required keyword argument and internal block

### ISSUE THREAD

**Issue by kwstannard** [vim-ruby/vim-ruby#304]
Bad indenting with trailing required keyword argument:
``` ruby
foo do |bar:|
  herp do
end
end

foo do |bar: nil, baz:|
  herp do
end
end
```
Indenting works if the final keyword argument is not required.
``` ruby
foo do |bar:, baz: nil|
  herp do
  end
end
```
Indenting also works with procs and methods.
``` ruby
->(bar: nil, baz:) do
  herp do
  end
end

def foo(bar: nil, baz:)
  herp do
  end
end
```

**Comment by AndrewRadev** [comment]
Tricky issue. The problem is that the `|` at the end ends up being considered as a bitwise or operator, but only when considered as a "parent" of the line that matches the "end".

Long story short, I've added an additional check to the relevant regexes that the pipe should not be preceded by a `:` in order to be considered a bitwise-or pipe. Could you try it out and let me know if it works for you (and whether you see any other related issues caused by the fix)?

**Comment by kwstannard** [comment]
That worked! Thanks! I don't know if I can think of anything that might this might cause problems for off the top of my head either.
```
foo do |bar:|
  herp do
  end
end

foo do |baz: nil, bar:|
  herp do
  end
end

foo do |bar: nil|
  herp do
  end
end

->(bar: nil, baz:) do
  herp do
  end
end

def foo(bar: nil, baz:)
  herp do
  end
end
```
