### ISSUE TITLE
Incorrect completion

### ISSUE THREAD

**Issue by graywolf** [vim-ruby/vim-ruby#325]
With following snippet

    module Test
    	A = 0
    	B = 1
    end
    
    def foo
    	return Test::<CTRL-X><CTRL-O>
    end

I would expect to get `A` and `B` as suggestiong, instead I get `Pattern not found`.

**Comment by AndrewRadev** [comment]
Thanks to @Isty001's PR, #372, this issue should be fixed. @graywolf, could you try it out with the latest master and check if your example works now?

**Comment by AndrewRadev** [comment]
Ordinarily, yes. I've actually managed to find and fix the problem, I think. 

The solution is implemented in https://github.com/vim-ruby/vim-ruby/commit/36b67afb8e593794e05cf72e494bcc11f255ca21, and I'd appreciate if @dkearns could review it. For the moment, though, I think it should fix the bug, @graywolf. Could you test it out?

**Comment by graywolf** [comment]
@AndrewRadev the fix does solve my issue, however as you already said in the commit message, I have not idea if there will be any side effects. Did not notice any so far however I did not have much time to test this yet.

**Comment by AndrewRadev** [comment]
Well, given it seems to work for you, I'll go ahead and close this issue. If you run into problems that seem related, consider reopening, or opening a new one.

**Comment by dkearns** [comment]
@AndrewRadev Sorry for not getting to this earlier.

The fix for the second issue mentioned might actually be worse as it'll now abort the parsing at the first "end", or even "}", apparently in the module.  I.E., at best, the end of the first method definition.

Perhaps the best quick solution is to assume proper formatting and match the indent?

I don't actually use the omni completion and have never contributed to it.  I just noticed it had some outstanding pull requests and needed some love so was checking back through the issue history.

**Comment by AndrewRadev** [comment]
Yes, I realized just after posting that you weren't the author, sorry. Don't know why I was under that impression.

I *think* that it won't stop at the first `end`, because it's a `searchpairpos`, so it would look for an `end` matching the first part (`a:type`, which should be `class` or `module` or whatever), while respecting nesting. I will test this out over the weekend.

**Comment by AndrewRadev** [comment]
Ah, no, that wouldn't be right -- it would have to be a regex including *all* of the possibilities for an `end`-starter. Maybe that's the solution (I think that's what we do in indentation).

**Comment by dkearns** [comment]
Yes, that was a 'slower' solution but if you already have the pattern... :)

**Comment by AndrewRadev** [comment]
Fixed by https://github.com/vim-ruby/vim-ruby/commit/f8200082a2ec44f7c45192523506787c13d30942, hopefully. It seems to find the correct `end` now at the very least.
