### ISSUE TITLE
Incorrect indentation for chained methods with multi-line arguments

### ISSUE THREAD

**Issue by vais** [vim-ruby/vim-ruby#328]
```ruby
class KeywordNormalizer
  def call(keywords)
    Collection.new(keywords)
      .strip_outer_punctuation
      .fix_spanish(
    one: two,
    three: four,
    five: six
    )
      .clean_inner_punctuation
      .remove_stop_words
      .to_a
  end
end
```
😕

**Comment by AndrewRadev** [comment]
I've pushed a commit that fixes the indentation of the keyword arguments. With it, the code now looks like this:

``` ruby
class KeywordNormalizer
  def call(keywords)
    Collection.new(keywords)
      .strip_outer_punctuation
      .fix_spanish(
        one: two,
        three: four,
        five: six
    )
      .clean_inner_punctuation
      .remove_stop_words
      .to_a
  end
end
```

The bracket still looks weird, but it's a difficult one to deal with. The short story is, you should probably put this in your .vimrc:

``` vim
let g:ruby_indent_block_style = 'do'
```

This will hopefully adjust the indentation of the bracket to look reasonable with your coding style.

It's an unintuitive name, since it doesn't really have anything to do with blocks in this case. Not sure what to do about it. The documentation for the setting is here: https://github.com/vim-ruby/vim-ruby/blob/1b4a95db4931317a34fb55091624a4f976728264/doc/vim-ruby.txt#L116

**Comment by AndrewRadev** [comment]
Actually, there still seems to be an issue with detecting the right line. I'll see if there's anything I can do.

**Comment by vais** [comment]
Awesome, @AndrewRadev, thank you for looking into this! And thanks for the tip re `let g:ruby_indent_block_style = 'do'` - I had no idea that was an option, I'll investigate if it makes the indenter work more like I expect. Again, thanks!
