### ISSUE TITLE
Syntax highlight does not work well with large heredocs

### ISSUE THREAD

**Issue by graywolf** [vim-ruby/vim-ruby#376]
I have `.erb` file with heredoc spanning about 3.5k lines and when I'm near the end and try to make new line (by either `o` in command or enter key in input) vim freezes for about 0.75s. It's not making it unusable, just highly annoying.

My CPU is not a complete shit (`Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz`) so I wonder if there is room for some optimization. It's just one huge string

```
<<~EOF
...
EOF
```

so no highlighting is being done inside so I'm not sure what's taking so long :/

PS: deleting line is fast as normal.

**Comment by tpope** [comment]
You could try playing with `:help :syn-sync`.

**Comment by tpope** [comment]
Actually the first step you should do is verify your assumption that it's the syntax highlighting to blame and not the indenting or something else.

**Comment by AndrewRadev** [comment]
It's very likely to be indentation. You can confirm it by pressing `==` on the last line of the heredoc. It's still a valid issue, just not caused by syntax highlighting, probably.

**Comment by graywolf** [comment]
@tpope since `syntax off` makes it fast again, I assume it's caused by the syntax highlighting? I did not find combination of setting that would allow me to has syntax visible while still being fast.

I've attached simplest possible reproduction case. When you are on line 8194 and press `o` it takes a whil before new line is inserted. However with `syntax off` it's nearly instant.

[376.erb.tar.gz](https://github.com/vim-ruby/vim-ruby/files/2246424/376.erb.tar.gz)

**Comment by AndrewRadev** [comment]
It's true that you that you can fix the issue by turning syntax off, but, in your example, I am able to fix the issue also by doint `set indentexpr=`. This disables vim-ruby's indentation, which is why pressing `o` is slow.

The problem is that indentation goes over every single line above in the string to find the first one that *isn't* a string. Thankfully, looking over the code, I *think* we don't actually need to do this. I've pushed an optimization in this particular case. @graywolf, could you try again and see if the performance is better?

**Comment by graywolf** [comment]
Thank you so much, I very much understand that my use case is on bit of a weird side here, not many people do things like this. 8d95b5f8c7986df7b2d8ca36a42006bc6a493ef8 fixes my issue without any downsides I could notice. Thank you very much!
