### ISSUE TITLE
Icorrect Indentation for FFI's typedef function

### ISSUE THREAD

**Issue by jimfoltz** [vim-ruby/vim-ruby#399]
FFI has a `typedef` function which incorrectly indents as follows when using the vim `=` command

```ruby
   typedef(:pointer, :int_ptr)
      typedef(:pointer, :double_ptr)
         typedef(:pointer, :size_ptr)
```
Thanks. Using latest gvim 8.1 on Windows 10 (via scoop) if it matters.

**Comment by AndrewRadev** [comment]
I can't seem to replicate the issue, if I just put these lines in a ruby file and indent them, they end up like this:

``` ruby
typedef(:pointer, :int_ptr)
typedef(:pointer, :double_ptr)
typedef(:pointer, :size_ptr)
```

Could you try to put these lines in a separate file and indent them? I'm wondering if it's the context of the lines somehow, what surrounds them.

Also, could you try the master version of the plugin instead of the one that comes with Vim? You can install it as any other plugin and it'll take priority.

**Comment by jimfoltz** [comment]
I tried both of your suggestions but no luck. I use pathogen and cloned `vim-ruby` to the `bundle` folder. I'm not sure how to verify vim is loading the latest version. of `vim-ruby` I assume so since the other vim plugins such as `lightline.vim` is being loaded from the same folder.

 I'm looking at my configuration for something else amiss.  In the meantime, [here](https://github.com/jimfoltz/jf-sketchup-ffi/blob/master/lib/sketchup-ffi.rb) is the file.

**Comment by jimfoltz** [comment]
After purging some rarely used options and plugins from my `vimrc`, the problem has gone away.  I'll close this for now but will report again if I find out what the cause was. Thanks.

**Comment by AndrewRadev** [comment]
It would definitely be useful to know what it was, so yes, give us an update if you ever find out.
