### ISSUE TITLE
Comment with @ and "end" keyword breaks indentation

### ISSUE THREAD

**Issue by b-nik** [vim-ruby/vim-ruby#400]
I'm using vim-ruby from vim-polyglot on Vim 8.1-1967

When a comment starts with @ and contains the word "end", the following indentation breaks

Minimal example (with the wrong indentation)

```ruby
class A
  def test
    # @Note random words with the end keyword
    a = 3

    a
end

def foo
  x = 4
  x if x > 3
end
end
```

Replacing the above comment with any of the following won't cause the bug
```ruby
# @Note random words with the END keyword
# @Note random words with the keyword
# text @Note random words with the end keyword
```

**Comment by AndrewRadev** [comment]
This seems to be a vim-polyglot issue -- I can't replicate the problem with the vim-ruby codebase, unless I add vim-polyglot to my bundle.

Interestingly, I don't think the problem is in an older version or something -- it seems they have their own syntax extension for yard comments: https://github.com/sheerun/vim-polyglot/blob/4f3df59be709bf0d5c5c67dc804fde49abdc2700/after/syntax/ruby.vim

My assumption is that this interferes with the "is it a string or comment" helper function: https://github.com/vim-ruby/vim-ruby/blob/1aa8f0cd0411c093d81f4139d151f93808e53966/indent/ruby.vim#L692-L694

I'd recommend you open an issue to vim-polyglot or maybe to the [vim-yard](https://github.com/sheerun/vim-yardoc) project and link to this issue for the explanation. If they follow the function calls, they might figure out some way to rename their syntax groups so indentation doesn't break. I'd be open to making some changes to help them out, but I'm not sure what they'd be in this particular situation.

**Comment by AndrewRadev** [comment]
As a workaround, you could disable this particular vim-polyglot extension by adding `"yard"` to `g:polyglot_disabled`: https://github.com/sheerun/vim-polyglot/blob/4f3df59be709bf0d5c5c67dc804fde49abdc2700/after/syntax/ruby.vim#L1

**Comment by b-nik** [comment]
Thanks, and sorry, I didn't realize there was a yard script also!  I've disabled it, and now it works.

The yard plugin seems abandoned, so no reason to add an issue there I think.
