### ISSUE TITLE
Extra ^H characters in ri documentation

### ISSUE THREAD

**Issue by marselmustafin** [vim-ruby/vim-ruby#411]
I see ri documentation titles with the following extra ^H characters when use `K` command:
 
![image](https://user-images.githubusercontent.com/19539397/75615999-29862f00-5b5c-11ea-8857-6e83205513b1.png)

Is there a way to get rid of them?

**Comment by tpope** [comment]
Wild guess but are you using Neovim?

**Comment by marselmustafin** [comment]
@tpope yep

**Comment by tpope** [comment]
Given that this whole project exists to be integrated with mainline Vim, I don't think we want to touch this? I certainly wouldn't want to email Bram a file with a `has('nvim')` check in it. @dkearns is the one who actually has to send that email and if he has different ideas I would love to hear them. Otherwise, I recommend one of the following workarounds:

* Add `:set keywordprg=ri` to `.vim/after/ftplugin/ruby.vim`.
* Find/invent a plugin that re-implements `K` to use `:terminal`.
