### ISSUE TITLE
`E363: pattern uses more memory than 'maxmempattern'` with long strings

### ISSUE THREAD

**Issue by renatolond** [vim-ruby/vim-ruby#412]
Hi!
I've been experiencing issues with long strings but I can't seem to find a reproducible way to find which patterns are causing the issue.

I have some ruby files with very long strings and neovim v0.4.3 starts to complain about maxmempattern.

I tried to create a file which simulates the error, here it goes:

```
# frozen_string_literal: true

require "date"

module A
  module B
    A_CONST = "nice-string-constant-here"
    B_CONST = "#{A_CONST}/NICE!"
    C_CONST = "#{A_CONST}/COOL!"

    def self.func(a)
      my_hash = {
        "a" => "b",
        "foo" => "bar"
        "A-NOT-Managed-Strings" => "ABCDEfghe910dmckamks019292djdjOOOjjjd/cr3wdCA+1n/xHfHMgG+cC0EoUNngcBjgWvBMEF1CurBwTtDswJjQYa5wYRAQEBAQECCwGwAQEvI50CnwMNAwRrAQYBr9PPAoK7sQMBAQMCBAkICAQIAwEBAwYBAQQFFQEBAhQDAwMDCwEBAQUBAQHGAQEWBAEBDecBfS8CHQEKkAEMMxcMCQoUDwYHIjd3DQ4MFk0JWGYALSKLAQOLAYEBFBAjCBGDAQICAgMANjsZAg9fCxkCgLZKAwSEAQIBiwEZGAsrBCgFMmUEJShyFSfRBQEOSQY62AG0AVlCrQ",
        "another" => "string",
        "and yet" => "another",
        "cool string" => "to use",
        "yeah" => "neat",
        "cool cool" => "stuff",
        "there we go" => "yeah"
      }

      my_hash["cool"] = "stuff"
      my_hash["nice"] = "things"
      my_hash["has stuff"] = "inside"

      my_hash
    end

    def self.another_func
      a = Date.new

      hash = func(a)

      hash["yey"] = "woo-hoo"
    end
  end
end
```

Seems the issue is with the `A-NOT-Managed-Strings` value, since if you remove the issue goes away.

**Comment by AndrewRadev** [comment]
I believe I've narrowed down the issue to this particular pattern for `rubySymbol`: https://github.com/vim-ruby/vim-ruby/blob/871e7a16dcb5a9c1ce8ae34978d6922e804e3472/syntax/ruby.vim#L464

In the example, it doesn't even match, it fails, but it seems maybe the search for the pattern breaks regardless. It's used for, among other things, the `bar:` in

``` vim
def foo(bar:)
end
```

A possible solution is suggested by the Vim docs -- replace the `\@<=` with a `\zs`. This seems to work as a pattern, and it highlights the above, but the tests break on these two cases:

``` ruby
foo { |bar:| 42 }

h = {
  x:
    really_long_method_name,
  y: 5,
}
```

The `bar:` and `x:` don't get highlighted. Instead, their groups are, respectively, `rubyBlockParameterList` and `rubyCurlyBlock`. My assumption is there's a subtle difference here in `\zs` and `\@<=` in terms of containment within other groups or something.

At this point, I have no good solution to the problem other to ask @dkearns for ideas. I also still don't quite understand why this only fails on the long string line, since it doesn't seem related to the pattern.

**Comment by AndrewRadev** [comment]
Hm, okay, replacing this bit at the end: `*[?!]\=::\@!` with `\{,19}[?!]\=::\@!` also works, though obviously only for symbols with less than 20 characters, which is not exactly workable. But it helps me sort of understand the reason this is happening -- The pattern `\%(\h\|[^\x00-\x7F]\)\%(\w\|[^\x00-\x7F]\)*` is supposed to match up with the symbol body, but only if it's later followed by `:`. This means that, in order to be able to backtrack, the engine needs to keep that entire part in memory until it hits the `:` or something else.

When it gets to the long string, it turns out it actually matches that "symbol body" part, and the regex has to give up when it doesn't find a `:` at the end. I'm not sure why it matches, and why it doesn't match with a `\zs`. There's this part in the docs:

> "\@<=" and "\@<!" check for matches just before what follows.
> Theoretically these matches could start anywhere before this position.
> But to limit the time needed, only the line where what follows matches
> is searched, and one line before that (if there is one).  This should
> be sufficient to match most things and not be too slow.

So, maybe it looks for all the "symbol body" parts first and then it attempts to find the start of a match before them or not, which ends up being applied to the long string. Which is why there's no problem with `\zs`, because the logic of that one is to first match the first part, and then just sort of ignore it. But because that first part was already matched as a delimiter (a hash-starter, a block-argument-starter), the engine can't "see" it, it's already consumed.

**Comment by AndrewRadev** [comment]
@dkearns This is a PR that seems to pass the tests: https://github.com/vim-ruby/vim-ruby/pull/413. No idea if it would work out for all other cases -- it's difficult for me to tease out which of the three lines handles which cases, and it even feels like there's some overlap.

**Comment by AndrewRadev** [comment]
@renatolond I've merged the PR I was referring to above, so I think this issue should be fixed now. I'll go ahead and close it, but please reopen if you encounter the issue again, or if you see something that looks related.

**Comment by renatolond** [comment]
Thanks Andrew, I'll check and let you know :)
