### ISSUE TITLE
rails completion doesn't work because of wrong LOAD_PATH

### ISSUE THREAD

**Issue by r03** [vim-ruby/vim-ruby#414]
I'm trying to get omnicomplete working for rails 6.
I have the same problem with vim 8.1 (with ruby) and neovim 0.3.4

These are the settings:
```
let g:rubycomplete_buffer_loading = 1
let g:rubycomplete_classes_in_global = 1
let g:rubycomplete_rails = 1
```

in neovim I added this for rbenv with ruby 2.6.6:
```
let g:ruby_host_prog = '~/.rbenv/shims/neovim-ruby-host'  " gem install neovim
let g:ruby_path = system('echo $HOME/.rbenv/shims')
```
In Vim 8 I tried with the system ruby without rbenv (Debian 10, ruby 2.5.5)

I always get the error 'pattern not found'

When debugging vim with `vim -V9myvim.log` I get this error:

> Error loading rails environment
> Pattern not found

I tried writing to a log file inside dprint and it seems to crash after loading `environment.rb` with this error:

> Rails Error uninitialized constant Spring
> input val
> default/other
> inclass == nil

I also tried a manual script to try emulate the problem, but this script works:

```
require 'rubygems'
require './config/boot.rb'
require './config/environment.rb'
puts Rails.env
```
What is vim-ruby doing different than this?

Any tips? Thanks for the help.

**Comment by r03** [comment]
It works if I put these in comment:

```
    #$:.push rails_base unless $:.index( rails_base )

    rails_config = rails_base + "config/"
    rails_lib = rails_base + "lib/"
    #$:.push rails_config unless $:.index( rails_config )
    #$:.push rails_lib unless $:.index( rails_lib )
```

**Comment by r03** [comment]
This is a simulation of the error:
```
$:.push "."
$:.push "./config"
$:.push "./lib"
require "rubygems"
require "./config/boot.rb"
require "./config/environment.rb"
puts Rails.env
```
Any idea why these path are added to the LOAD_PATH? Seems to be added 14 years ago.
Maybe I can add a parameter with the option to disable this?

**Comment by AndrewRadev** [comment]
Good work debugging the issue -- thanks for putting in the effort. It might be that these lines are there because they were necessary for some old rails version, but end up breaking a modern setup. I would actually just consider removing them completely -- an option "add local paths" feels like it might be confusing -- in what circumstances would I want to add local paths and what would be the consequences?

Unfortunately, I've never managed to get ruby omnicompletion quite working, but I'd like to experiment a bit before removing those lines. I'll see what I can do.

Which rails version are you testing with, by the way? I just managed to replicate it with a rails 5.2 app, wondering if it's the same for rails 6, for instance.

**Comment by r03** [comment]
I was testing with a new rails 6 app.
I also prefer to remove those lines, but I don't know if that will cause
problems for other people.

**Comment by r03** [comment]
I wonder how many people use omnicompletion for Rails.
A combination of syntaxcompletion and tagcompletion may get better results. (and faster)
But because this railscompletion now fails there is also no syntaxcompletion.

Maybe the best solution is to just remove those lines and if there is still an error fall back to syntaxcompletion? (with an extra message that rails could not be loaded)

**Comment by AndrewRadev** [comment]
Honestly, I don't see why they're added, other than for convenience in requiring files maybe? I'm not sure. 

The reason the error is happening is because of this code in the application file: `Bundler.require(*Rails.groups)`. So, this tries to `require 'spring'`, I imagine, and that loads the `spring.rb` file under `config` instead of the one in the gem.

I'm going to remove these two lines and hope for the best. If people open issues about errors, we'll see what we can do, I guess. But I feel like if there's issues, they shouldn't be solved like this -- adding `config` to the load path could easily cause similar namespace conflicts.

**Comment by AndrewRadev** [comment]
Pushed to master -- let me know if you run into other problems that seem related.
