### ISSUE TITLE
Vim-ruby resets the local option `tags` sometimes, wiping out values added by other plugins

### ISSUE THREAD

**Issue by tomdalling** [vim-ruby/vim-ruby#425]
While [investigating why Gutentags stopped working sometimes](https://github.com/ludovicchabant/vim-gutentags/issues/289), I tracked down the problem to [b:undo_ftplugin within vim-ruby](https://github.com/vim-ruby/vim-ruby/blob/fbf85d106a2c3979ed43d6332b8c26a72542754d/ftplugin/ruby.vim#L136-L138).

Gutentags adds paths the the local `tags` option, which are later wiped out when `b:undo_ftplugin` is executed. Jumping to a tag and back again with `<c-]><c-o>` to is triggering the execution of `b:undo_ftplugin`, which permanently removes the tag file functionality from the buffer.

It would be better if vim-ruby only removed the paths from `tags` that were added by vim-ruby, instead of resetting the option.

Any thoughts on an easy way to fix this?

**Comment by tpope** [comment]
Taking a quick peak at source, Gutentags has its own broken filetype handling. `g:gutentags_exclude_filetypes` allows disabling for particular filetypes, but [it performs that check on whatever filetype happens to be set when the buffer is loaded](https://github.com/ludovicchabant/vim-gutentags/blob/8e69652c7a7e7aabd96cff21b6ee6b6a295c901c/autoload/gutentags.vim#L260-L264). If the initial filetype isn't excluded, but the new filetype is, Gutentags will nevertheless remain enabled. This is a pretty obscure edge case, to be sure, but   if it was handled correctly, by manipulating the `'tags'` option on every `FileType` event, this would require no special considerations in vim-ruby. It's tough to come up with a usage for the buffer local `tags` option that *doesn't* boil down to the file type, which is why it felt appropriate to implement this way.

That said, I can't see a downside to selectively removing paths as you propose as long as it is done robustly (a medium-to-large if). Feel free to take a stab at it.

**Comment by tomdalling** [comment]
Sounds reasonable. Thanks for taking a look at it.

If resetting `tags` like this is common practice then I think it makes more sense to handle it in Gutentags. I can see some Gutentags issues that look similar but for other filetypes, which might be the same problem. Now I'm leaning towards just patching this with an `autocmd` myself, because fixing this in Gutentags seems kind of complicated.

Anyway, thanks again. I'll close this one.

**Comment by tpope** [comment]
It's the standard behavior for option restoring in general, but `ftplugin/ruby.vim` is the only standard runtime file that does it for `'tags'` in particular. I carefully weighed the options when adding it because I was aware I was in uncharted territory.
