### ISSUE TITLE
Incorrectly indenting next line after an endless method

### ISSUE THREAD

**Issue by cstyles** [vim-ruby/vim-ruby#432]
Ruby 3 introduced endless methods like this:

```ruby
def square(x) = x * x
```

But when I create a new line after an endless method definition (either with `o` or pressing enter/return in Insert mode), it indents the following line like this:

```ruby
def square(x) = x * x
  def sum(x) = x + x
```

The desired indentation would be on the same level as the line above it, like this:

```ruby
def square(x) = x * x
def sum(x) = x + x
```

**Comment by AndrewRadev** [comment]
I've created some initial support for this feature in the branch `endless-def`. The PR is https://github.com/vim-ruby/vim-ruby/pull/433

I'm going to use this separate branch for a while to see if anything existing gets broken, because I feel like there's a lot of potential for that happening. So far I'm not seeing anything (other than the reported existing issues, that is 😅).

@cstyles Could you also switch to the branch and use it for a while? It would also be great if you can think of some weird edge cases to exercise it. You can see the things I've experimented with here: https://github.com/vim-ruby/vim-ruby/pull/433/files#diff-c97f8e7cebd688b684c982490aac30fa231618dce63fd9f17c8d68acaff9292dR43-R64

**Comment by AndrewRadev** [comment]
The change is master now, let's see if there's any complaints.

**Comment by AndrewRadev** [comment]
I'm going to consider this resolved for the moment. Doug did point out a potential issue in the PR (https://github.com/vim-ruby/vim-ruby/pull/433#issuecomment-882639065), but I feel like it's exotic enough that it wouldn't be a problem, and it might be kind of tricky to resolve. We'll see if there's complaints.

**Comment by ntl** [comment]
I am trying this out, and it seems to work for instance methods, but not class methods. See the screenshot, where the cursor is indented:

![Screenshot from 2022-06-29 16-20-22](https://user-images.githubusercontent.com/31915/176547034-9709365a-b0c0-4dcd-b5d5-badc50a01980.png)
