### ISSUE TITLE
[Neovim/Vim] Replaying macro broken

### ISSUE THREAD

**Issue by DawidJanczak** [vim-ruby/vim-ruby#455]
Hello,

Something is off with a specific macro I'm trying in a `.html.erb` file and I think it's connected to this mapping https://github.com/vim-ruby/vim-ruby/blob/master/ftplugin/ruby.vim#L198

Given a file `foo.html.erb` with the following (simplified) content:
```
<img src="<%= APP_CONFIG[:public_assets] %>/images/first.jpg" alt="some alt 1">
<img src="<%= APP_CONFIG[:public_assets] %>/images/second.jpg" alt="some alt 2">
```

Open it with `nvim -u NORC` to avoid loading plugins, but still load default Vim ones from this repo. Then
1. Type `/`, search for `APP` and press enter to get to the first occurrence.
2. `qa` to record the following macro: `2cf/image_tag("<esc>f"a) %>"<esc>` and finally `q` to stop recording
3. Press `n` to go to the next occurrence and `@a` to replay the macro.

Instead of getting the same result as on the first line, the second line changes to the following:
```
<img src="<%= call <SNR>81_wrap_i('[m',']M')
age_tag("second.jpg") %>" alt="some alt 2">
```

Vim version details:
```
❯ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I'm on Neovim, but double checked that the same thing occurs on normal Vim 9 as well.

If I do not load `ftplugin/ruby.vim` and `ftplugin/eruby.vim` the macro works fine.

**Comment by AndrewRadev** [comment]
This is very fascinating, and is very likely a core Vim bug. It might be an old one, or some patch that was shared between Vim and Neovim.

It's easy to replicate outside of vim-ruby, doesn't even need macros. I can put the following in a file called test.vim:

``` vim
" One two targeT

onoremap <buffer> fo BUG
```

Putting the cursor in the beginning of `two` and executing `normal cfTfour` results, as expected, in `" One four`. Sourcing the file with `:source %` and then executing `normal cfTfour` again results in `" One BUGur`. This is me trying it out on a `vim --clean`.
There seems to be an existing issue that covers it: https://github.com/vim/vim/issues/6350. There's a PR that fixes it and I confirm it fixes your problem with the macro: https://github.com/vim/vim/pull/12708

However, it doesn't fix the problem when executing it with `normal` 😅. Still, it's something. It was opened a week ago, and it'll probably take time to review, since I'm guessing people are having vacations and stuff.

**Comment by DawidJanczak** [comment]
Oh that's super interesting, thanks for explaining this @AndrewRadev :) Given this isn't a bug with vim-ruby I'll close this issue.
