### ISSUE TITLE
 ]m is not working if set syntax=off

### ISSUE THREAD

**Issue by vds2212** [vim-ruby/vim-ruby#464]
The `]m` relies on the `searchsyn` method that relies on `set syntax=on`.

On Neovim if  [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) is installed then `set syntax=off` which makes the `]m` action not working.

For Python a regular expression approach has been followed:
```
let b:next_toplevel='\v%$\|^(class\|def)>'
let b:prev_toplevel='\v^(class\|def)>'
let b:next_endtoplevel='\v%$\|\S.*\n+(def\|class)'
let b:prev_endtoplevel='\v\S.*\n+(def\|class)'
let b:next='\v%$\|^\s*(class\|def)>'
let b:prev='\v^\s*(class\|def)>'
let b:next_end='\v\S\n*(%$\|^(\s*\n*)*(class\|def)\|^\S)'
let b:prev_end='\v\S\n*(^(\s*\n*)*(class\|def)\|^\S)'

if !exists('g:no_plugin_maps') && !exists('g:no_ruby_maps')
    " execute "nnoremap <silent> <buffer> ]] :<C-U>call <SID>Ruby_jump('n', '". b:next_toplevel."', 'W', v:count1)<cr>"
    " execute "nnoremap <silent> <buffer> [[ :<C-U>call <SID>Ruby_jump('n', '". b:prev_toplevel."', 'Wb', v:count1)<cr>"
    " execute "nnoremap <silent> <buffer> ][ :<C-U>call <SID>Ruby_jump('n', '". b:next_endtoplevel."', 'W', v:count1, 0)<cr>"
    " execute "nnoremap <silent> <buffer> [] :<C-U>call <SID>Ruby_jump('n', '". b:prev_endtoplevel."', 'Wb', v:count1, 0)<cr>"
    " execute "nnoremap <silent> <buffer> ]m :<C-U>call <SID>Ruby_jump('n', '". b:next."', 'W', v:count1)<cr>"
    " execute "nnoremap <silent> <buffer> [m :<C-U>call <SID>Ruby_jump('n', '". b:prev."', 'Wb', v:count1)<cr>"
    " execute "nnoremap <silent> <buffer> ]M :<C-U>call <SID>Ruby_jump('n', '". b:next_end."', 'W', v:count1, 0)<cr>"
    " execute "nnoremap <silent> <buffer> [M :<C-U>call <SID>Ruby_jump('n', '". b:prev_end."', 'Wb', v:count1, 0)<cr>"

    " execute "onoremap <silent> <buffer> ]] :call <SID>Ruby_jump('o', '". b:next_toplevel."', 'W', v:count1)<cr>"
    " execute "onoremap <silent> <buffer> [[ :call <SID>Ruby_jump('o', '". b:prev_toplevel."', 'Wb', v:count1)<cr>"
    " execute "onoremap <silent> <buffer> ][ :call <SID>Ruby_jump('o', '". b:next_endtoplevel."', 'W', v:count1, 0)<cr>"
    " execute "onoremap <silent> <buffer> [] :call <SID>Ruby_jump('o', '". b:prev_endtoplevel."', 'Wb', v:count1, 0)<cr>"
    " execute "onoremap <silent> <buffer> ]m :call <SID>Ruby_jump('o', '". b:next."', 'W', v:count1)<cr>"
    " execute "onoremap <silent> <buffer> [m :call <SID>Ruby_jump('o', '". b:prev."', 'Wb', v:count1)<cr>"
    " execute "onoremap <silent> <buffer> ]M :call <SID>Ruby_jump('o', '". b:next_end."', 'W', v:count1, 0)<cr>"
    " execute "onoremap <silent> <buffer> [M :call <SID>Ruby_jump('o', '". b:prev_end."', 'Wb', v:count1, 0)<cr>"

    " execute "xnoremap <silent> <buffer> ]] :call <SID>Ruby_jump('x', '". b:next_toplevel."', 'W', v:count1)<cr>"
    " execute "xnoremap <silent> <buffer> [[ :call <SID>Ruby_jump('x', '". b:prev_toplevel."', 'Wb', v:count1)<cr>"
    " execute "xnoremap <silent> <buffer> ][ :call <SID>Ruby_jump('x', '". b:next_endtoplevel."', 'W', v:count1, 0)<cr>"
    " execute "xnoremap <silent> <buffer> [] :call <SID>Ruby_jump('x', '". b:prev_endtoplevel."', 'Wb', v:count1, 0)<cr>"
    " execute "xnoremap <silent> <buffer> ]m :call <SID>Ruby_jump('x', '". b:next."', 'W', v:count1)<cr>"
    " execute "xnoremap <silent> <buffer> [m :call <SID>Ruby_jump('x', '". b:prev."', 'Wb', v:count1)<cr>"
    " execute "xnoremap <silent> <buffer> ]M :call <SID>Ruby_jump('x', '". b:next_end."', 'W', v:count1, 0)<cr>"
    " execute "xnoremap <silent> <buffer> [M :call <SID>Ruby_jump('x', '". b:prev_end."', 'Wb', v:count1, 0)<cr>"
endif

if !exists('*<SID>Ruby_jump')
  fun! <SID>Ruby_jump(mode, motion, flags, count, ...) range
      let l:startofline = (a:0 >= 1) ? a:1 : 1

      if a:mode == 'x'
          normal! gv
      endif

      if l:startofline == 1
          normal! 0
      endif

      let cnt = a:count
      mark '
      while cnt > 0
          call search(a:motion, a:flags)
          let cnt = cnt - 1
      endwhile

      if l:startofline == 1
          normal! ^
      endif
  endfun
endif
```

**Comment by AndrewRadev** [comment]
Replacing syntax-aware searching with regexes is not ideal. For instance, you can add this line to your example:

```
some_method = <<-EOF
  def boom
      print "Boom!\n"
  end
EOF
```

Searching for method definitions with `]m` will now jump to this string, even though it's not a method. The reason we rely on syntax is because of cases like this. The built-in syntax highlighting can build up a syntax tree with nested regions. Regex are useful for local pattern-matching, but we routinely use syntax groups to make sure we are matching the right place.

I agree with the maintainer that responded to you in the Neovim thread: If you want to fully use treesitter, then use treesitter queries to navigate. If you would prefer to rely on this implementation, then please enable native syntax highlighting. You could try this method of enabling additional syntax highlighting, although I don't know if this exact config is still relevant: https://github.com/vim-ruby/vim-ruby/issues/451#issuecomment-1178979909

Making this work via regexes would degrade the quality of the functionality, and you should be able to very easily avoid this issue on your end by enabling native syntax or by implementing tree-sitter-based navigation. I'm not going to close this issue at this time, because it's Tim Pope's file, and maybe he or the other maintainers feel differently about it, but I'll close it in a week if there are no dissenting opinions.

**Comment by AndrewRadev** [comment]
Actually, given this comment by Tim in this thread: https://github.com/vim-ruby/vim-ruby/issues/442#issuecomment-982004128

> The im map and indenting are both coupled to the syntax highlighting. If you're using different syntax highlighting, from treesitter or anywhere else, they'll break. I don't think there's anything we can do about this. Implementing without use of the syntax highlighting is somewhere between "difficult" and "impossible".

I'll go ahead and close this issue as not planned.

**Comment by vds2212** [comment]
Thanks @AndrewRadev, I understand the position.
